# Generated by Django 3.2.8 on 2021-10-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='originalURL',
            field=models.URLField(unique=True),
        ),
    ]
