# Generated by Django 3.2.8 on 2021-10-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_shorturl_originalurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='originalURL',
            field=models.URLField(),
        ),
    ]
